# -*- coding: utf-8 -*-
"""simple linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_prSRdLrj1rXOniYVxe_2e2mgbWE2Ob
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

flights = sns.load_dataset("flights")

flights.head()
flights.info()
flights.shape

flights.describe()

flights.plot(kind = "box")
plt.show

sns.scatterplot(x = "year", y = "passengers", data = flights)
plt.show()

from sklearn.model_selection import train_test_split

x = flights["year"].values.reshape(-1,1)
y = flights["passengers"]

xtrain, xtest, ytrain, ytest = train_test_split(x, y,test_size = 0.3, random_state= 20)

xtrain

from sklearn.linear_model import LinearRegression
model = LinearRegression()

lr = LinearRegression()
lr.fit(xtrain, ytrain)

ypred = lr.predict(xtest)

plt.scatter(xtest, ytest, color = "blue")
plt.plot(xtest, ypred, color = "red")
plt.show()